[algokit]
min_version = "v2.0.0"

[project]
type = 'contract'
name = 'algorand-contracts'
artifacts = 'contracts/artifacts'

[project.deploy]
command = "node deploy.js"

[project.deploy.testnet]
environment_secrets = ["DEPLOYER_MNEMONIC"]

[project.run]
build = { commands = [ 
  'npm run build',
], description = 'Build all smart contracts in the project' }
test = { commands = [
  'npm run test',
], description = 'Run smart contract tests' }
deploy = { commands = [
  'node deploy.js',
], description = 'Deploy smart contracts to network' }
